
version: "3.9"

services:
  db:
    image: mariadb:10.6
    container_name: eddji-db
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      - ./mariadb-data:/var/lib/mysql
    networks:
      - eddji-net

  redis-cache:
    image: redis:6
    container_name: eddji-redis-cache
    restart: unless-stopped
    networks:
      - eddji-net

  redis-queue:
    image: redis:6
    container_name: eddji-redis-queue
    restart: unless-stopped
    networks:
      - eddji-net

  redis-socketio:
    image: redis:6
    container_name: eddji-redis-socketio
    restart: unless-stopped
    networks:
      - eddji-net

  backend:
    image: frappe/erpnext:version-15
    container_name: eddji-backend
    restart: unless-stopped
    depends_on:
      - db
      - redis-cache
      - redis-queue
      - redis-socketio
    environment:
      SITE_NAME: ${SITE_NAME}
      DB_HOST: ${DB_HOST}
      DB_ROOT_USER: root
      DB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      REDIS_CACHE: redis-cache:6379
      REDIS_QUEUE: redis-queue:6379
      REDIS_SOCKETIO: redis-socketio:6379
    volumes:
      - ./sites:/home/frappe/frappe-bench/sites
    networks:
      - eddji-net
    ports:
      - "8080:8000"

  nginx-gateway:
    image: nginx:latest
    container_name: eddji-nginx
    restart: unless-stopped
    depends_on:
      - backend
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/logs:/var/log/nginx
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    networks:
      - eddji-net
    ports:
      - "80:80"
      - "443:443"

  certbot:
    image: certbot/certbot
    container_name: eddji-certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    networks:
      - eddji-net

networks:
  eddji-net:
    driver: bridge
